### ISSUE TITLE
Porting the core

### ISSUE THREAD

**Issue by DFL1973** [Grabulosaure/Intv_MiSTer#3]
Sorry for use this space to contact you.

I'm porting your core to another pcb, but I'm confused about the "ioctl_wait" signal. (Sorry, I don't have a MisTer to make the tests.)

Is that signal used to get some pause between each byte read from SD and the write on BRAM? I saw some CRCs calcs and I'm assuming if the SD too fast, the core will miss the writes. Is this correct? 

Thanks for sharing. Intv is one of my all-time favorite consoles.

**Comment by Grabulosaure** [comment]
Well, the MiSTer framework isn't fully documented, and it's still evolving.
The wait signal is used to add some delay after every byte, and, at the beginning, to give time to clear all memory.

Currently, the finite state machine that handles dataloading (ReadROM) needs one wait cycle after every ioctl_wr='1' to handle the different file formats, steer data... It could probably be optimized.
If you can add a delay between every write, then you don't need the wait signal (and clearing memory isn't always needed, but, sometimes, some homebrew games only developed on emulators doesn't properly initialize all used memory)

The CRC is used to calculate a signature, these CRCs are compared to a few known values for games with unusual memory mappings:
https://docs.google.com/spreadsheets/d/1SE-URZLioX19FIbmX200VBaKcCyuv-NCPKt56Hf37Fk/edit#gid=0

**Comment by DFL1973** [comment]
Thanks for the info! I will try to add some delays.

And thanks again for sharing your amazing work.

**Comment by DFL1973** [comment]
Sorry to bother you again. I believe the ioclt_downloading is fine now, but I still can't figure out why it's not working. I don't have enough BRAM to allocate 65535 16 bits, so I'm trying to use an SDRAM.

I replaced both processes that write/read on BRAM to the below code. I even tried to reduce the ReadROM speed to half of the clock (a second clock created dividing clksys), but no go either.

As I understood, that BRAM works as RAM and ROM, so besides the initial writing, the data is moved to upper positions according to the mapping. Is this correct?

I believe it will be very easy to port to the MisT if that BRAM could be replaced for the SDRAM.

Best regards and thanks for the help

-------

addr_s <= "00000000" & std_logic_vector(w_a) & '0'   		when ioctl_download = '1' else "00000000" & std_logic_vector(cad) & '0';
	din_s	 <= std_logic_vector(w_d) & std_logic_vector(w_d)  when ioctl_download = '1' else std_logic_vector(cart_dw);
	wtbt_s <= (w_wrh & w_wrl) 										 	when ioctl_download = '1' else "11";
	
	sdram1 : sdram
	port map
	(
		-- interface to the MT48LC16M16 chip
		SDRAM_A    		=> SDRAM_A,
		SDRAM_DQ    	=> SDRAM_DQ,
		SDRAM_nCS      => SDRAM_nCS,
		SDRAM_BA      	=> SDRAM_BA,
		SDRAM_nWE      => SDRAM_nWE,
		SDRAM_nRAS     => SDRAM_nRAS,
		SDRAM_nCAS     => SDRAM_nCAS,
		SDRAM_CKE     	=> SDRAM_CKE,
		SDRAM_DQML     => SDRAM_DQML,
		SDRAM_DQMH     => SDRAM_DQMH,
			
		clk        		=> clksys,
		init       		=> not pll_locked,
		wtbt      		=> wtbt_s , --16 bits

		addr       		=> addr_s,
		din        		=> din_s,
		unsigned(dout(15 downto 8)) => cart_drh,
		unsigned(dout( 7 downto 0)) => cart_drl,
		rd    			=> rden, --???
		we         		=> w_wrh or w_wrl or cart_wrm,
		ready          => open
	);

**Comment by Grabulosaure** [comment]
The core implements the "Intellicart" which is/was a programmable cartridge wich could be downloaded from a serial port and emulate original game carts. The Intellicart supports programmable memory configuration (which zones are ROM, which are RAM).
When not using the intellicart format, data is stored contiguously then mapped according to the "standard" mappings (0...9).
You can try first to test with reduced memory size, most original games fit in 32kB = 16kWords, only new homebrews use all memory.

The SDRAM should be fast enough to replace internal RAM.
A "read" signal will be needed to trigger read accesses to SDRAM (while reads are continuous in the current implementation using internal RAM), probably something derived from `phi` and `stic/prd`. I can try to find it.

**Comment by DFL1973** [comment]
Thanks for the reply. for the tests, I changed the following lines as suggested
  SHARED VARIABLE cartl : arr_uv8(0 TO 16383);
  SHARED VARIABLE carth : arr_uv8(0 TO 16383);
I'm using some .BINs, since I understand that files with the first byte as 0xA8 are the Intellicart files.

Following the ReadRom process, my ioctl_addr start with 0x0000 and add 1 after each byte read. (I believe this is the expect behaviour), so, that WHEN prepape the signals w_wrl, w_wrh and w_a and the CartH2 process write the bytes on 0 to 16386 area (as example using Pittifall.bin, a 8Kb file, I'm guessing it´s using 0 to 4096 on each of cartl and carth)

BUT... still not working... :(
The screen doesn't show any change, and it looks like you dont have any cart (I saw some Mister videos, and it's identical when the core is loaded first time, no carts selected). After my ioctl_download, it´s like a reset, like the core just started without any carts.

Is the CartH1 process writes on that area even if it 's a standard BIN? or that process pushes the (as example) Pitfall.bin to an upper address?

**Comment by Grabulosaure** [comment]
I have posted test bench files and execution logs (CPU trace & video output) for Pitfall.
http://temlib.org/pub/mister/intv
When running Pitfall, the default mapping is used (mmap=0) : CPU address AD=0x5000 => CAD=0x0000. Data is always downloaded into cart memory from address zero, it is the mapping table (icart_map) file that transforms addresses. Either it is one of the ten "standard" mappings, or it is defined in the intellicart formatted file.

If mmap=0 : 
```
x"00",x"00",x"00",x"00",x"00",x"00",x"00",x"00",x"00",x"00",x"00",x"08",x"10",x"18",x"00",x"00",x"00",x"00",x"00",x"00",x"00",x"00",x"00",x"00",x"00",x"00",x"20",x"28",x"00",x"00",x"30",x"38"

5000 = x"00" = 0000,  5800 = x"08" = 0800
6000 = x"10" = 1000,  6800 = x"18" = 1800
D000 = x"20" = 2000,  D800 = x"28" = 2800
F000 = x"30" = 3000,  F800 = x"38" = 3800
```

The CPU runs first the internal firmware in ROM (EXECROM, address=0x1000) before branching to the cart.

**Comment by DFL1973** [comment]
Wow, really helpful!
I believe I can finish the port now.

Many, many thanks!

**Comment by DFL1973** [comment]
Just to report back, it´s working now, thanks for your great support.

I only saw a minor issue, on Pittfal, inside the game, all the scenario greens and yellow turns into a solid green, so up to middle screen, you see only the black hollows and brown logs. 
It´s possible to see the man's shirt and the head, but as the pants are green, is missing on the scene. The color palette appears to be ok on the initial screen (Activision presents).

The other games I tested appear to be ok.

**Comment by Grabulosaure** [comment]
Great! Congratulations.

I have pushed a fix for Pitfall. A few other games don't work, don't hesitate to signal any issue.

**Comment by DFL1973** [comment]
Hi! Thanks, worked like a charm.

The other issue I saw was Donkey Kong with invisible barrels, but this same
Pitfall fix already fixes the DK.

Many thanks!

Em dom., 5 de jan. de 2020 às 20:58, Grabulosaure <notifications@github.com>
escreveu:
